import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "./(components)/trpc";
import { HydrateClient } from "@/trpc/next";
import { getSessionFromNextCookies } from "@/session";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSessionFromNextCookies();

  return (
    <html lang="en">
      <body>
        <Provider session={session}>
          <HydrateClient>{children}</HydrateClient>
        </Provider>
      </body>
    </html>
  );
}
